apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingesolab2-frontend-deployment
  labels:
    app: tingesolab2-frontend-deployment
spec:
  selector:
    matchLabels:
      app: tingesolab2-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tingesolab2-frontend-deployment
    spec:
      containers:
      - name: tingesolab2-frontend
        image: ovejazo/tingesolab2-frontend:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tingesolab2-frontend-service
  labels:
    app: tingesolab2-frontend
spec:
  selector:
    app: tingesolab2-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer