apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frecuencclents-deployment
  labels:
    app: ms-frecuencclents-deployment
spec:
  selector:
    matchLabels:
      app: ms-frecuencclents-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-frecuencclents-deployment
    spec:
      containers:
        - name: frecuencclentsms
          image: ovejazo/frecuencclents
          ports:
            - containerPort: 8093