apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-fee-deployment
  labels:
    app: ms-fee-deployment
spec:
  selector:
    matchLabels:
      app: ms-fee-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-fee-deployment
    spec:
      containers:
        - name: feems
          image: ovejazo/feems
          ports:
            - containerPort: 8092