apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-report-deployment
  labels:
    app: ms-report-deployment
spec:
  selector:
    matchLabels:
      app: ms-report-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-report-deployment
    spec:
      containers:
        - name: reportms
          image: ovejazo/reportms
          ports:
            - containerPort: 8097