apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-rack-deployment
  labels:
    app: ms-rack-deployment
spec:
  selector:
    matchLabels:
      app: ms-rack-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-rack-deployment
    spec:
      containers:
        - name: rackms
          image: ovejazo/rackms
          ports:
            - containerPort: 8096